/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const PersonId = IDL.Text;
export const StewardRoleStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Removed' : IDL.Null,
});
export const StewardRecord = IDL.Record({
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Principal,
  'stewardAccountId' : IDL.Principal,
  'successorPriority' : IDL.Opt(IDL.Nat),
  'roleStatus' : StewardRoleStatus,
});
export const StewardError = IDL.Variant({
  'LastSteward' : IDL.Null,
  'NotSteward' : IDL.Null,
  'AlreadySteward' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'NotApprovedClaimedMember' : IDL.Null,
  'NotDesignated' : IDL.Null,
});
export const Result_8 = IDL.Variant({
  'ok' : StewardRecord,
  'err' : StewardError,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoId = IDL.Nat;
export const Photo = IDL.Record({
  'id' : PhotoId,
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const RelationshipType = IDL.Variant({
  'Parent' : IDL.Null,
  'Sibling' : IDL.Null,
  'SpousePartner' : IDL.Null,
  'Child' : IDL.Null,
});
export const RelationshipStatus = IDL.Variant({
  'Disputed' : IDL.Null,
  'Confirmed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Relationship = IDL.Record({
  'id' : IDL.Nat,
  'status' : RelationshipStatus,
  'fromPersonId' : PersonId,
  'toPersonId' : PersonId,
  'relationshipType' : RelationshipType,
});
export const RelationshipAdminError = IDL.Variant({
  'RelationshipNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'DuplicateRelationship' : IDL.Null,
  'PersonNotFound' : IDL.Null,
});
export const Result_16 = IDL.Variant({
  'ok' : Relationship,
  'err' : RelationshipAdminError,
});
export const ArchiveItemId = IDL.Nat;
export const ArchiveItemStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const PrivacyLevel = IDL.Variant({
  'Private' : IDL.Null,
  'Public' : IDL.Null,
  'FamilyOnly' : IDL.Null,
});
export const ArchiveItemType = IDL.Variant({
  'Research' : IDL.Null,
  'Photo' : IDL.Null,
  'Document' : IDL.Null,
  'WorkBusiness' : IDL.Null,
  'WrittenStoryNote' : IDL.Null,
  'Audio' : IDL.Null,
  'Other' : IDL.Null,
  'Video' : IDL.Null,
});
export const SourceStatus = IDL.Variant({
  'Copy' : IDL.Null,
  'Unverified' : IDL.Null,
  'Transcribed' : IDL.Null,
  'Original' : IDL.Null,
});
export const ArchiveItem = IDL.Record({
  'id' : ArchiveItemId,
  'era' : IDL.Text,
  'status' : ArchiveItemStatus,
  'title' : IDL.Text,
  'relatedMemberIds' : IDL.Vec(IDL.Text),
  'blob' : ExternalBlob,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'year' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'privacyLevel' : PrivacyLevel,
  'itemType' : ArchiveItemType,
  'relatedBranchId' : IDL.Opt(IDL.Text),
  'sourceStatus' : SourceStatus,
  'contributor' : IDL.Principal,
});
export const ProfileClaimStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ProfileClaim = IDL.Record({
  'id' : IDL.Nat,
  'submittedDate' : IDL.Int,
  'status' : ProfileClaimStatus,
  'reviewedDate' : IDL.Opt(IDL.Int),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'personId' : PersonId,
  'requestingUserId' : IDL.Principal,
});
export const ProfileRemovalStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const ProfileRemovalRequest = IDL.Record({
  'id' : IDL.Nat,
  'submittedDate' : IDL.Int,
  'status' : ProfileRemovalStatus,
  'reviewedDate' : IDL.Opt(IDL.Int),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'personId' : PersonId,
  'requestingUserId' : IDL.Principal,
  'reason' : IDL.Text,
});
export const RelationshipRequestStatus = IDL.Variant({
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'Pending' : IDL.Null,
});
export const RelationshipRequest = IDL.Record({
  'id' : IDL.Nat,
  'submittedDate' : IDL.Int,
  'status' : RelationshipRequestStatus,
  'reviewedDate' : IDL.Opt(IDL.Int),
  'relatedPersonId' : PersonId,
  'requestingPersonId' : PersonId,
  'proposedRelationship' : RelationshipType,
  'reviewer' : IDL.Opt(IDL.Principal),
});
export const ArchiveError = IDL.Variant({
  'NotArchived' : IDL.Null,
  'ProfileNotFound' : IDL.Null,
  'AlreadyArchived' : IDL.Null,
  'NotSignedIn' : IDL.Null,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ArchiveError });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuthMethod = IDL.Variant({
  'Google' : IDL.Null,
  'Apple' : IDL.Null,
});
export const AccountId = IDL.Principal;
export const Account = IDL.Record({
  'id' : AccountId,
  'createdAt' : IDL.Int,
  'authMethods' : IDL.Vec(AuthMethod),
});
export const AccountError = IDL.Variant({
  'AccountNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
});
export const Result_17 = IDL.Variant({ 'ok' : Account, 'err' : AccountError });
export const ClaimStatus = IDL.Variant({
  'Unclaimed' : IDL.Null,
  'Claimed' : IDL.Null,
});
export const LivingStatus = IDL.Variant({
  'Living' : IDL.Null,
  'Deceased' : IDL.Null,
});
export const PersonProfile = IDL.Record({
  'occupation' : IDL.Opt(IDL.Text),
  'privacySettings' : IDL.Opt(IDL.Text),
  'nickname' : IDL.Opt(IDL.Text),
  'claimedByUserId' : IDL.Opt(IDL.Principal),
  'birthDate' : IDL.Opt(IDL.Text),
  'birthInfo' : IDL.Opt(IDL.Text),
  'claimStatus' : ClaimStatus,
  'livingStatus' : LivingStatus,
  'name' : IDL.Text,
  'longerStory' : IDL.Opt(IDL.Text),
  'personId' : PersonId,
  'story' : IDL.Opt(IDL.Text),
  'middleName' : IDL.Opt(IDL.Text),
  'suffix' : IDL.Opt(IDL.Text),
  'preferredName' : IDL.Opt(IDL.Text),
  'currentLocation' : IDL.Opt(IDL.Text),
  'birthplace' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'shortBio' : IDL.Opt(IDL.Text),
  'timeline' : IDL.Opt(IDL.Vec(IDL.Text)),
  'firstName' : IDL.Opt(IDL.Text),
});
export const CreateError = IDL.Variant({ 'NotSignedIn' : IDL.Null });
export const Result_15 = IDL.Variant({
  'ok' : PersonProfile,
  'err' : CreateError,
});
export const SuccessorStatus = IDL.Variant({
  'Activated' : IDL.Null,
  'Removed' : IDL.Null,
  'Designated' : IDL.Null,
});
export const SuccessorDesignation = IDL.Record({
  'status' : SuccessorStatus,
  'assignedAt' : IDL.Int,
  'assignedBy' : IDL.Principal,
  'personId' : PersonId,
  'priority' : IDL.Nat,
});
export const Result_14 = IDL.Variant({
  'ok' : SuccessorDesignation,
  'err' : StewardError,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result__1 = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Result_13 = IDL.Variant({
  'ok' : AccountId,
  'err' : AccountError,
});
export const AuthMethods = IDL.Record({
  'apple' : IDL.Bool,
  'google' : IDL.Bool,
});
export const Result_12 = IDL.Variant({
  'ok' : AuthMethods,
  'err' : AccountError,
});
export const AuditActionType = IDL.Variant({
  'ProfileRemovalRequested' : IDL.Null,
  'ClaimRejected' : IDL.Null,
  'RelationshipTypeCorrected' : IDL.Null,
  'RelationshipRequestPending' : IDL.Null,
  'StewardPromoted' : IDL.Null,
  'SuccessorActivated' : IDL.Null,
  'StewardRemoved' : IDL.Null,
  'RelationshipRequestApproved' : IDL.Null,
  'DuplicateMerged' : IDL.Null,
  'ProfilePermanentlyDeleted' : IDL.Null,
  'RelationshipRequestRejected' : IDL.Null,
  'ProfileArchived' : IDL.Null,
  'ProfileRestored' : IDL.Null,
  'RelationshipAdded' : IDL.Null,
  'RelationshipRemoved' : IDL.Null,
  'ProfileRemovalReviewed' : IDL.Null,
  'ClaimApproved' : IDL.Null,
  'SuccessorDesignated' : IDL.Null,
});
export const AuditEntry = IDL.Record({
  'id' : IDL.Nat,
  'affectedPersonIds' : IDL.Vec(PersonId),
  'actionType' : AuditActionType,
  'summary' : IDL.Text,
  'timestamp' : IDL.Int,
  'actorAccountId' : IDL.Principal,
});
export const DuplicateCandidate = IDL.Record({
  'deathDate' : IDL.Opt(IDL.Text),
  'ownerAccount' : IDL.Opt(IDL.Principal),
  'birthDate' : IDL.Opt(IDL.Text),
  'claimStatus' : IDL.Text,
  'name' : IDL.Text,
  'archiveLinks' : IDL.Vec(IDL.Text),
  'children' : IDL.Vec(IDL.Text),
  'sourceCount' : IDL.Nat,
  'personId' : PersonId,
  'spouses' : IDL.Vec(IDL.Text),
  'photoCount' : IDL.Nat,
  'timelineCount' : IDL.Nat,
  'parents' : IDL.Vec(IDL.Text),
});
export const DuplicatePair = IDL.Record({
  'candidateA' : DuplicateCandidate,
  'candidateB' : DuplicateCandidate,
});
export const StewardIdentity = IDL.Record({
  'accountId' : IDL.Principal,
  'displayName' : IDL.Text,
  'personId' : PersonId,
  'canonicalName' : IDL.Text,
});
export const NotificationType = IDL.Variant({
  'RelationshipRequested' : IDL.Null,
  'RelationshipReviewed' : IDL.Null,
  'ProfileClaimReviewed' : IDL.Null,
  'ProfileClaimRequested' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notificationType' : NotificationType,
  'createdAt' : IDL.Int,
  'read' : IDL.Bool,
  'recipient' : IDL.Principal,
  'message' : IDL.Text,
});
export const NotificationId = IDL.Nat;
export const MergeConflictStatus = IDL.Variant({
  'Resolved' : IDL.Null,
  'Pending' : IDL.Null,
});
export const MergeConflict = IDL.Record({
  'id' : IDL.Nat,
  'field' : IDL.Text,
  'status' : MergeConflictStatus,
  'alternateValue' : IDL.Text,
  'canonicalValue' : IDL.Text,
  'resolvedAt' : IDL.Opt(IDL.Int),
  'resolvedBy' : IDL.Opt(IDL.Principal),
});
export const MergeResult = IDL.Record({
  'archivedPersonId' : PersonId,
  'conflicts' : IDL.Vec(MergeConflict),
  'canonicalPersonId' : PersonId,
});
export const MergeError = IDL.Variant({
  'NotDuplicate' : IDL.Null,
  'ProfileNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'SameProfile' : IDL.Null,
});
export const Result_11 = IDL.Variant({
  'ok' : MergeResult,
  'err' : MergeError,
});
export const Result_10 = IDL.Variant({ 'ok' : IDL.Null, 'err' : MergeError });
export const DeleteError = IDL.Variant({
  'HasOwnershipHistory' : IDL.Null,
  'ProfileNotFound' : IDL.Null,
  'HasMedia' : IDL.Null,
  'HasArchiveItems' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'ConfirmationRequired' : IDL.Null,
  'HasTimeline' : IDL.Null,
  'HasApprovedRelationships' : IDL.Null,
});
export const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : DeleteError });
export const RelationshipError = IDL.Variant({
  'DuplicateRequest' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'PersonNotFound' : IDL.Null,
});
export const Result_7 = IDL.Variant({
  'ok' : RelationshipRequest,
  'err' : RelationshipError,
});
export const RemoveError = IDL.Variant({
  'ProfileNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
});
export const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : RemoveError });
export const Result_5 = IDL.Variant({
  'ok' : IDL.Null,
  'err' : RelationshipAdminError,
});
export const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : StewardError });
export const ClaimError = IDL.Variant({
  'AlreadyPending' : IDL.Null,
  'ProfileNotFound' : IDL.Null,
  'AlreadyClaimed' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'DeceasedProfile' : IDL.Null,
});
export const Result_3 = IDL.Variant({
  'ok' : ProfileClaim,
  'err' : ClaimError,
});
export const RemovalError = IDL.Variant({
  'AlreadyPending' : IDL.Null,
  'ProfileNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'NotOwner' : IDL.Null,
  'DeceasedProfile' : IDL.Null,
});
export const Result_2 = IDL.Variant({
  'ok' : ProfileRemovalRequest,
  'err' : RemovalError,
});
export const PersonMatch = IDL.Record({
  'name' : IDL.Text,
  'personId' : PersonId,
  'parents' : IDL.Vec(IDL.Text),
});
export const ProfileEdits = IDL.Record({
  'occupation' : IDL.Opt(IDL.Text),
  'privacySettings' : IDL.Opt(IDL.Text),
  'nickname' : IDL.Opt(IDL.Text),
  'birthDate' : IDL.Opt(IDL.Text),
  'birthInfo' : IDL.Opt(IDL.Text),
  'livingStatus' : IDL.Opt(LivingStatus),
  'longerStory' : IDL.Opt(IDL.Text),
  'story' : IDL.Opt(IDL.Text),
  'middleName' : IDL.Opt(IDL.Text),
  'suffix' : IDL.Opt(IDL.Text),
  'preferredName' : IDL.Opt(IDL.Text),
  'currentLocation' : IDL.Opt(IDL.Text),
  'birthplace' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Opt(IDL.Text),
  'shortBio' : IDL.Opt(IDL.Text),
  'timeline' : IDL.Opt(IDL.Vec(IDL.Text)),
  'firstName' : IDL.Opt(IDL.Text),
});
export const EditError = IDL.Variant({
  'ProfileNotFound' : IDL.Null,
  'NotSignedIn' : IDL.Null,
  'NotOwner' : IDL.Null,
  'DeceasedProfile' : IDL.Null,
});
export const Result = IDL.Variant({ 'ok' : PersonProfile, 'err' : EditError });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'activateSuccessor' : IDL.Func([PersonId], [Result_8], []),
  'addPhoto' : IDL.Func(
      [PersonId, IDL.Text, IDL.Text, ExternalBlob],
      [Photo],
      [],
    ),
  'addRelationship' : IDL.Func(
      [PersonId, PersonId, RelationshipType],
      [Result_16],
      [],
    ),
  'approveArchiveItem' : IDL.Func([ArchiveItemId], [IDL.Opt(ArchiveItem)], []),
  'approveProfileClaim' : IDL.Func([IDL.Nat], [IDL.Opt(ProfileClaim)], []),
  'approveProfileRemoval' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProfileRemovalRequest)],
      [],
    ),
  'approveRelationshipRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RelationshipRequest)],
      [],
    ),
  'archiveProfile' : IDL.Func([PersonId], [Result_1], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bindAuthMethod' : IDL.Func([AuthMethod], [Result_17], []),
  'correctRelationshipType' : IDL.Func(
      [IDL.Nat, RelationshipType],
      [Result_16],
      [],
    ),
  'createMyself' : IDL.Func([IDL.Text], [Result_15], []),
  'designateSuccessor' : IDL.Func([PersonId, IDL.Nat], [Result_14], []),
  'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAccountId' : IDL.Func([], [Result_13], ['query']),
  'getMyAuthMethods' : IDL.Func([], [Result_12], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(PersonProfile)], ['query']),
  'getMyProfileClaim' : IDL.Func(
      [PersonId],
      [IDL.Opt(ProfileClaim)],
      ['query'],
    ),
  'getMyRelationshipRequests' : IDL.Func(
      [],
      [IDL.Vec(RelationshipRequest)],
      ['query'],
    ),
  'getPersonProfile' : IDL.Func(
      [PersonId],
      [IDL.Opt(PersonProfile)],
      ['query'],
    ),
  'getProfilePhoto' : IDL.Func([PersonId], [IDL.Opt(Photo)], ['query']),
  'getRelationshipRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RelationshipRequest)],
      ['query'],
    ),
  'getSingleStewardWarning' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovedArchiveItems' : IDL.Func([], [IDL.Vec(ArchiveItem)], ['query']),
  'listArchivedProfileIds' : IDL.Func([], [IDL.Vec(PersonId)], ['query']),
  'listArchivedProfiles' : IDL.Func([], [IDL.Vec(PersonProfile)], ['query']),
  'listAuditHistory' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
  'listConfirmedRelationships' : IDL.Func(
      [],
      [IDL.Vec(Relationship)],
      ['query'],
    ),
  'listDuplicateCandidates' : IDL.Func([], [IDL.Vec(DuplicatePair)], ['query']),
  'listEligibleStewardCandidates' : IDL.Func(
      [],
      [IDL.Vec(StewardIdentity)],
      ['query'],
    ),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listPendingArchiveItems' : IDL.Func([], [IDL.Vec(ArchiveItem)], ['query']),
  'listPersonRelationships' : IDL.Func(
      [PersonId],
      [IDL.Vec(Relationship)],
      ['query'],
    ),
  'listPhotos' : IDL.Func([PersonId], [IDL.Vec(Photo)], ['query']),
  'listProfileClaims' : IDL.Func([], [IDL.Vec(ProfileClaim)], ['query']),
  'listProfileRemovalRequests' : IDL.Func(
      [],
      [IDL.Vec(ProfileRemovalRequest)],
      ['query'],
    ),
  'listRelationshipRequests' : IDL.Func(
      [],
      [IDL.Vec(RelationshipRequest)],
      ['query'],
    ),
  'listStewardIdentities' : IDL.Func([], [IDL.Vec(StewardIdentity)], ['query']),
  'listStewards' : IDL.Func([], [IDL.Vec(StewardRecord)], ['query']),
  'listSuccessors' : IDL.Func([], [IDL.Vec(SuccessorDesignation)], ['query']),
  'markNotificationRead' : IDL.Func(
      [NotificationId],
      [IDL.Opt(Notification)],
      [],
    ),
  'mergeProfiles' : IDL.Func([PersonId, PersonId], [Result_11], []),
  'notDuplicate' : IDL.Func([PersonId, PersonId], [Result_10], []),
  'permanentlyDeleteProfile' : IDL.Func([PersonId, IDL.Bool], [Result_9], []),
  'promoteToSteward' : IDL.Func([PersonId], [Result_8], []),
  'proposeRelationship' : IDL.Func(
      [PersonId, PersonId, RelationshipType],
      [Result_7],
      [],
    ),
  'rejectArchiveItem' : IDL.Func([ArchiveItemId], [IDL.Opt(ArchiveItem)], []),
  'rejectProfileClaim' : IDL.Func([IDL.Nat], [IDL.Opt(ProfileClaim)], []),
  'rejectProfileRemoval' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ProfileRemovalRequest)],
      [],
    ),
  'rejectRelationshipRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RelationshipRequest)],
      [],
    ),
  'removeDuplicateProfile' : IDL.Func([PersonId], [Result_6], []),
  'removePhoto' : IDL.Func([PersonId, PhotoId], [IDL.Bool], []),
  'removeRelationship' : IDL.Func([IDL.Nat], [Result_5], []),
  'removeSteward' : IDL.Func([IDL.Principal], [Result_4], []),
  'requestProfileClaim' : IDL.Func([PersonId], [Result_3], []),
  'requestProfileRemoval' : IDL.Func([PersonId, IDL.Text], [Result_2], []),
  'resolveMergeConflict' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Opt(MergeConflict)],
      [],
    ),
  'restoreProfile' : IDL.Func([PersonId], [Result_1], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchPossibleMatches' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PersonMatch)],
      ['query'],
    ),
  'setProfilePhoto' : IDL.Func([PersonId, PhotoId], [IDL.Opt(Photo)], []),
  'setRelationshipRequestPending' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RelationshipRequest)],
      [],
    ),
  'submitArchiveItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ArchiveItemType,
        ExternalBlob,
        IDL.Text,
        IDL.Opt(IDL.Nat),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        SourceStatus,
        PrivacyLevel,
      ],
      [ArchiveItem],
      [],
    ),
  'updateOwnProfile' : IDL.Func([PersonId, ProfileEdits], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result_18 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const PersonId = IDL.Text;
  const StewardRoleStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Removed' : IDL.Null,
  });
  const StewardRecord = IDL.Record({
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Principal,
    'stewardAccountId' : IDL.Principal,
    'successorPriority' : IDL.Opt(IDL.Nat),
    'roleStatus' : StewardRoleStatus,
  });
  const StewardError = IDL.Variant({
    'LastSteward' : IDL.Null,
    'NotSteward' : IDL.Null,
    'AlreadySteward' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'NotApprovedClaimedMember' : IDL.Null,
    'NotDesignated' : IDL.Null,
  });
  const Result_8 = IDL.Variant({ 'ok' : StewardRecord, 'err' : StewardError });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoId = IDL.Nat;
  const Photo = IDL.Record({
    'id' : PhotoId,
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const RelationshipType = IDL.Variant({
    'Parent' : IDL.Null,
    'Sibling' : IDL.Null,
    'SpousePartner' : IDL.Null,
    'Child' : IDL.Null,
  });
  const RelationshipStatus = IDL.Variant({
    'Disputed' : IDL.Null,
    'Confirmed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Relationship = IDL.Record({
    'id' : IDL.Nat,
    'status' : RelationshipStatus,
    'fromPersonId' : PersonId,
    'toPersonId' : PersonId,
    'relationshipType' : RelationshipType,
  });
  const RelationshipAdminError = IDL.Variant({
    'RelationshipNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'DuplicateRelationship' : IDL.Null,
    'PersonNotFound' : IDL.Null,
  });
  const Result_16 = IDL.Variant({
    'ok' : Relationship,
    'err' : RelationshipAdminError,
  });
  const ArchiveItemId = IDL.Nat;
  const ArchiveItemStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const PrivacyLevel = IDL.Variant({
    'Private' : IDL.Null,
    'Public' : IDL.Null,
    'FamilyOnly' : IDL.Null,
  });
  const ArchiveItemType = IDL.Variant({
    'Research' : IDL.Null,
    'Photo' : IDL.Null,
    'Document' : IDL.Null,
    'WorkBusiness' : IDL.Null,
    'WrittenStoryNote' : IDL.Null,
    'Audio' : IDL.Null,
    'Other' : IDL.Null,
    'Video' : IDL.Null,
  });
  const SourceStatus = IDL.Variant({
    'Copy' : IDL.Null,
    'Unverified' : IDL.Null,
    'Transcribed' : IDL.Null,
    'Original' : IDL.Null,
  });
  const ArchiveItem = IDL.Record({
    'id' : ArchiveItemId,
    'era' : IDL.Text,
    'status' : ArchiveItemStatus,
    'title' : IDL.Text,
    'relatedMemberIds' : IDL.Vec(IDL.Text),
    'blob' : ExternalBlob,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'year' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'privacyLevel' : PrivacyLevel,
    'itemType' : ArchiveItemType,
    'relatedBranchId' : IDL.Opt(IDL.Text),
    'sourceStatus' : SourceStatus,
    'contributor' : IDL.Principal,
  });
  const ProfileClaimStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ProfileClaim = IDL.Record({
    'id' : IDL.Nat,
    'submittedDate' : IDL.Int,
    'status' : ProfileClaimStatus,
    'reviewedDate' : IDL.Opt(IDL.Int),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'personId' : PersonId,
    'requestingUserId' : IDL.Principal,
  });
  const ProfileRemovalStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const ProfileRemovalRequest = IDL.Record({
    'id' : IDL.Nat,
    'submittedDate' : IDL.Int,
    'status' : ProfileRemovalStatus,
    'reviewedDate' : IDL.Opt(IDL.Int),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'personId' : PersonId,
    'requestingUserId' : IDL.Principal,
    'reason' : IDL.Text,
  });
  const RelationshipRequestStatus = IDL.Variant({
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const RelationshipRequest = IDL.Record({
    'id' : IDL.Nat,
    'submittedDate' : IDL.Int,
    'status' : RelationshipRequestStatus,
    'reviewedDate' : IDL.Opt(IDL.Int),
    'relatedPersonId' : PersonId,
    'requestingPersonId' : PersonId,
    'proposedRelationship' : RelationshipType,
    'reviewer' : IDL.Opt(IDL.Principal),
  });
  const ArchiveError = IDL.Variant({
    'NotArchived' : IDL.Null,
    'ProfileNotFound' : IDL.Null,
    'AlreadyArchived' : IDL.Null,
    'NotSignedIn' : IDL.Null,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : ArchiveError });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuthMethod = IDL.Variant({ 'Google' : IDL.Null, 'Apple' : IDL.Null });
  const AccountId = IDL.Principal;
  const Account = IDL.Record({
    'id' : AccountId,
    'createdAt' : IDL.Int,
    'authMethods' : IDL.Vec(AuthMethod),
  });
  const AccountError = IDL.Variant({
    'AccountNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
  });
  const Result_17 = IDL.Variant({ 'ok' : Account, 'err' : AccountError });
  const ClaimStatus = IDL.Variant({
    'Unclaimed' : IDL.Null,
    'Claimed' : IDL.Null,
  });
  const LivingStatus = IDL.Variant({
    'Living' : IDL.Null,
    'Deceased' : IDL.Null,
  });
  const PersonProfile = IDL.Record({
    'occupation' : IDL.Opt(IDL.Text),
    'privacySettings' : IDL.Opt(IDL.Text),
    'nickname' : IDL.Opt(IDL.Text),
    'claimedByUserId' : IDL.Opt(IDL.Principal),
    'birthDate' : IDL.Opt(IDL.Text),
    'birthInfo' : IDL.Opt(IDL.Text),
    'claimStatus' : ClaimStatus,
    'livingStatus' : LivingStatus,
    'name' : IDL.Text,
    'longerStory' : IDL.Opt(IDL.Text),
    'personId' : PersonId,
    'story' : IDL.Opt(IDL.Text),
    'middleName' : IDL.Opt(IDL.Text),
    'suffix' : IDL.Opt(IDL.Text),
    'preferredName' : IDL.Opt(IDL.Text),
    'currentLocation' : IDL.Opt(IDL.Text),
    'birthplace' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'shortBio' : IDL.Opt(IDL.Text),
    'timeline' : IDL.Opt(IDL.Vec(IDL.Text)),
    'firstName' : IDL.Opt(IDL.Text),
  });
  const CreateError = IDL.Variant({ 'NotSignedIn' : IDL.Null });
  const Result_15 = IDL.Variant({ 'ok' : PersonProfile, 'err' : CreateError });
  const SuccessorStatus = IDL.Variant({
    'Activated' : IDL.Null,
    'Removed' : IDL.Null,
    'Designated' : IDL.Null,
  });
  const SuccessorDesignation = IDL.Record({
    'status' : SuccessorStatus,
    'assignedAt' : IDL.Int,
    'assignedBy' : IDL.Principal,
    'personId' : PersonId,
    'priority' : IDL.Nat,
  });
  const Result_14 = IDL.Variant({
    'ok' : SuccessorDesignation,
    'err' : StewardError,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result__1 = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Result_13 = IDL.Variant({ 'ok' : AccountId, 'err' : AccountError });
  const AuthMethods = IDL.Record({ 'apple' : IDL.Bool, 'google' : IDL.Bool });
  const Result_12 = IDL.Variant({ 'ok' : AuthMethods, 'err' : AccountError });
  const AuditActionType = IDL.Variant({
    'ProfileRemovalRequested' : IDL.Null,
    'ClaimRejected' : IDL.Null,
    'RelationshipTypeCorrected' : IDL.Null,
    'RelationshipRequestPending' : IDL.Null,
    'StewardPromoted' : IDL.Null,
    'SuccessorActivated' : IDL.Null,
    'StewardRemoved' : IDL.Null,
    'RelationshipRequestApproved' : IDL.Null,
    'DuplicateMerged' : IDL.Null,
    'ProfilePermanentlyDeleted' : IDL.Null,
    'RelationshipRequestRejected' : IDL.Null,
    'ProfileArchived' : IDL.Null,
    'ProfileRestored' : IDL.Null,
    'RelationshipAdded' : IDL.Null,
    'RelationshipRemoved' : IDL.Null,
    'ProfileRemovalReviewed' : IDL.Null,
    'ClaimApproved' : IDL.Null,
    'SuccessorDesignated' : IDL.Null,
  });
  const AuditEntry = IDL.Record({
    'id' : IDL.Nat,
    'affectedPersonIds' : IDL.Vec(PersonId),
    'actionType' : AuditActionType,
    'summary' : IDL.Text,
    'timestamp' : IDL.Int,
    'actorAccountId' : IDL.Principal,
  });
  const DuplicateCandidate = IDL.Record({
    'deathDate' : IDL.Opt(IDL.Text),
    'ownerAccount' : IDL.Opt(IDL.Principal),
    'birthDate' : IDL.Opt(IDL.Text),
    'claimStatus' : IDL.Text,
    'name' : IDL.Text,
    'archiveLinks' : IDL.Vec(IDL.Text),
    'children' : IDL.Vec(IDL.Text),
    'sourceCount' : IDL.Nat,
    'personId' : PersonId,
    'spouses' : IDL.Vec(IDL.Text),
    'photoCount' : IDL.Nat,
    'timelineCount' : IDL.Nat,
    'parents' : IDL.Vec(IDL.Text),
  });
  const DuplicatePair = IDL.Record({
    'candidateA' : DuplicateCandidate,
    'candidateB' : DuplicateCandidate,
  });
  const StewardIdentity = IDL.Record({
    'accountId' : IDL.Principal,
    'displayName' : IDL.Text,
    'personId' : PersonId,
    'canonicalName' : IDL.Text,
  });
  const NotificationType = IDL.Variant({
    'RelationshipRequested' : IDL.Null,
    'RelationshipReviewed' : IDL.Null,
    'ProfileClaimReviewed' : IDL.Null,
    'ProfileClaimRequested' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notificationType' : NotificationType,
    'createdAt' : IDL.Int,
    'read' : IDL.Bool,
    'recipient' : IDL.Principal,
    'message' : IDL.Text,
  });
  const NotificationId = IDL.Nat;
  const MergeConflictStatus = IDL.Variant({
    'Resolved' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const MergeConflict = IDL.Record({
    'id' : IDL.Nat,
    'field' : IDL.Text,
    'status' : MergeConflictStatus,
    'alternateValue' : IDL.Text,
    'canonicalValue' : IDL.Text,
    'resolvedAt' : IDL.Opt(IDL.Int),
    'resolvedBy' : IDL.Opt(IDL.Principal),
  });
  const MergeResult = IDL.Record({
    'archivedPersonId' : PersonId,
    'conflicts' : IDL.Vec(MergeConflict),
    'canonicalPersonId' : PersonId,
  });
  const MergeError = IDL.Variant({
    'NotDuplicate' : IDL.Null,
    'ProfileNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'SameProfile' : IDL.Null,
  });
  const Result_11 = IDL.Variant({ 'ok' : MergeResult, 'err' : MergeError });
  const Result_10 = IDL.Variant({ 'ok' : IDL.Null, 'err' : MergeError });
  const DeleteError = IDL.Variant({
    'HasOwnershipHistory' : IDL.Null,
    'ProfileNotFound' : IDL.Null,
    'HasMedia' : IDL.Null,
    'HasArchiveItems' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'ConfirmationRequired' : IDL.Null,
    'HasTimeline' : IDL.Null,
    'HasApprovedRelationships' : IDL.Null,
  });
  const Result_9 = IDL.Variant({ 'ok' : IDL.Null, 'err' : DeleteError });
  const RelationshipError = IDL.Variant({
    'DuplicateRequest' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'PersonNotFound' : IDL.Null,
  });
  const Result_7 = IDL.Variant({
    'ok' : RelationshipRequest,
    'err' : RelationshipError,
  });
  const RemoveError = IDL.Variant({
    'ProfileNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
  });
  const Result_6 = IDL.Variant({ 'ok' : IDL.Null, 'err' : RemoveError });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Null,
    'err' : RelationshipAdminError,
  });
  const Result_4 = IDL.Variant({ 'ok' : IDL.Null, 'err' : StewardError });
  const ClaimError = IDL.Variant({
    'AlreadyPending' : IDL.Null,
    'ProfileNotFound' : IDL.Null,
    'AlreadyClaimed' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'DeceasedProfile' : IDL.Null,
  });
  const Result_3 = IDL.Variant({ 'ok' : ProfileClaim, 'err' : ClaimError });
  const RemovalError = IDL.Variant({
    'AlreadyPending' : IDL.Null,
    'ProfileNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'NotOwner' : IDL.Null,
    'DeceasedProfile' : IDL.Null,
  });
  const Result_2 = IDL.Variant({
    'ok' : ProfileRemovalRequest,
    'err' : RemovalError,
  });
  const PersonMatch = IDL.Record({
    'name' : IDL.Text,
    'personId' : PersonId,
    'parents' : IDL.Vec(IDL.Text),
  });
  const ProfileEdits = IDL.Record({
    'occupation' : IDL.Opt(IDL.Text),
    'privacySettings' : IDL.Opt(IDL.Text),
    'nickname' : IDL.Opt(IDL.Text),
    'birthDate' : IDL.Opt(IDL.Text),
    'birthInfo' : IDL.Opt(IDL.Text),
    'livingStatus' : IDL.Opt(LivingStatus),
    'longerStory' : IDL.Opt(IDL.Text),
    'story' : IDL.Opt(IDL.Text),
    'middleName' : IDL.Opt(IDL.Text),
    'suffix' : IDL.Opt(IDL.Text),
    'preferredName' : IDL.Opt(IDL.Text),
    'currentLocation' : IDL.Opt(IDL.Text),
    'birthplace' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Opt(IDL.Text),
    'shortBio' : IDL.Opt(IDL.Text),
    'timeline' : IDL.Opt(IDL.Vec(IDL.Text)),
    'firstName' : IDL.Opt(IDL.Text),
  });
  const EditError = IDL.Variant({
    'ProfileNotFound' : IDL.Null,
    'NotSignedIn' : IDL.Null,
    'NotOwner' : IDL.Null,
    'DeceasedProfile' : IDL.Null,
  });
  const Result = IDL.Variant({ 'ok' : PersonProfile, 'err' : EditError });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result_18], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'activateSuccessor' : IDL.Func([PersonId], [Result_8], []),
    'addPhoto' : IDL.Func(
        [PersonId, IDL.Text, IDL.Text, ExternalBlob],
        [Photo],
        [],
      ),
    'addRelationship' : IDL.Func(
        [PersonId, PersonId, RelationshipType],
        [Result_16],
        [],
      ),
    'approveArchiveItem' : IDL.Func(
        [ArchiveItemId],
        [IDL.Opt(ArchiveItem)],
        [],
      ),
    'approveProfileClaim' : IDL.Func([IDL.Nat], [IDL.Opt(ProfileClaim)], []),
    'approveProfileRemoval' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProfileRemovalRequest)],
        [],
      ),
    'approveRelationshipRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RelationshipRequest)],
        [],
      ),
    'archiveProfile' : IDL.Func([PersonId], [Result_1], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bindAuthMethod' : IDL.Func([AuthMethod], [Result_17], []),
    'correctRelationshipType' : IDL.Func(
        [IDL.Nat, RelationshipType],
        [Result_16],
        [],
      ),
    'createMyself' : IDL.Func([IDL.Text], [Result_15], []),
    'designateSuccessor' : IDL.Func([PersonId, IDL.Nat], [Result_14], []),
    'execute' : IDL.Func([IDL.Text], [Result__1], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAccountId' : IDL.Func([], [Result_13], ['query']),
    'getMyAuthMethods' : IDL.Func([], [Result_12], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(PersonProfile)], ['query']),
    'getMyProfileClaim' : IDL.Func(
        [PersonId],
        [IDL.Opt(ProfileClaim)],
        ['query'],
      ),
    'getMyRelationshipRequests' : IDL.Func(
        [],
        [IDL.Vec(RelationshipRequest)],
        ['query'],
      ),
    'getPersonProfile' : IDL.Func(
        [PersonId],
        [IDL.Opt(PersonProfile)],
        ['query'],
      ),
    'getProfilePhoto' : IDL.Func([PersonId], [IDL.Opt(Photo)], ['query']),
    'getRelationshipRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RelationshipRequest)],
        ['query'],
      ),
    'getSingleStewardWarning' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovedArchiveItems' : IDL.Func(
        [],
        [IDL.Vec(ArchiveItem)],
        ['query'],
      ),
    'listArchivedProfileIds' : IDL.Func([], [IDL.Vec(PersonId)], ['query']),
    'listArchivedProfiles' : IDL.Func([], [IDL.Vec(PersonProfile)], ['query']),
    'listAuditHistory' : IDL.Func([], [IDL.Vec(AuditEntry)], ['query']),
    'listConfirmedRelationships' : IDL.Func(
        [],
        [IDL.Vec(Relationship)],
        ['query'],
      ),
    'listDuplicateCandidates' : IDL.Func(
        [],
        [IDL.Vec(DuplicatePair)],
        ['query'],
      ),
    'listEligibleStewardCandidates' : IDL.Func(
        [],
        [IDL.Vec(StewardIdentity)],
        ['query'],
      ),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listPendingArchiveItems' : IDL.Func([], [IDL.Vec(ArchiveItem)], ['query']),
    'listPersonRelationships' : IDL.Func(
        [PersonId],
        [IDL.Vec(Relationship)],
        ['query'],
      ),
    'listPhotos' : IDL.Func([PersonId], [IDL.Vec(Photo)], ['query']),
    'listProfileClaims' : IDL.Func([], [IDL.Vec(ProfileClaim)], ['query']),
    'listProfileRemovalRequests' : IDL.Func(
        [],
        [IDL.Vec(ProfileRemovalRequest)],
        ['query'],
      ),
    'listRelationshipRequests' : IDL.Func(
        [],
        [IDL.Vec(RelationshipRequest)],
        ['query'],
      ),
    'listStewardIdentities' : IDL.Func(
        [],
        [IDL.Vec(StewardIdentity)],
        ['query'],
      ),
    'listStewards' : IDL.Func([], [IDL.Vec(StewardRecord)], ['query']),
    'listSuccessors' : IDL.Func([], [IDL.Vec(SuccessorDesignation)], ['query']),
    'markNotificationRead' : IDL.Func(
        [NotificationId],
        [IDL.Opt(Notification)],
        [],
      ),
    'mergeProfiles' : IDL.Func([PersonId, PersonId], [Result_11], []),
    'notDuplicate' : IDL.Func([PersonId, PersonId], [Result_10], []),
    'permanentlyDeleteProfile' : IDL.Func([PersonId, IDL.Bool], [Result_9], []),
    'promoteToSteward' : IDL.Func([PersonId], [Result_8], []),
    'proposeRelationship' : IDL.Func(
        [PersonId, PersonId, RelationshipType],
        [Result_7],
        [],
      ),
    'rejectArchiveItem' : IDL.Func([ArchiveItemId], [IDL.Opt(ArchiveItem)], []),
    'rejectProfileClaim' : IDL.Func([IDL.Nat], [IDL.Opt(ProfileClaim)], []),
    'rejectProfileRemoval' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ProfileRemovalRequest)],
        [],
      ),
    'rejectRelationshipRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RelationshipRequest)],
        [],
      ),
    'removeDuplicateProfile' : IDL.Func([PersonId], [Result_6], []),
    'removePhoto' : IDL.Func([PersonId, PhotoId], [IDL.Bool], []),
    'removeRelationship' : IDL.Func([IDL.Nat], [Result_5], []),
    'removeSteward' : IDL.Func([IDL.Principal], [Result_4], []),
    'requestProfileClaim' : IDL.Func([PersonId], [Result_3], []),
    'requestProfileRemoval' : IDL.Func([PersonId, IDL.Text], [Result_2], []),
    'resolveMergeConflict' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(MergeConflict)],
        [],
      ),
    'restoreProfile' : IDL.Func([PersonId], [Result_1], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchPossibleMatches' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PersonMatch)],
        ['query'],
      ),
    'setProfilePhoto' : IDL.Func([PersonId, PhotoId], [IDL.Opt(Photo)], []),
    'setRelationshipRequestPending' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RelationshipRequest)],
        [],
      ),
    'submitArchiveItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ArchiveItemType,
          ExternalBlob,
          IDL.Text,
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          SourceStatus,
          PrivacyLevel,
        ],
        [ArchiveItem],
        [],
      ),
    'updateOwnProfile' : IDL.Func([PersonId, ProfileEdits], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };