/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : AccountId,
  'createdAt' : bigint,
  'authMethods' : Array<AuthMethod>,
}
export type AccountError = { 'AccountNotFound' : null } |
  { 'NotSignedIn' : null };
export type AccountId = Principal;
export type ArchiveError = { 'NotArchived' : null } |
  { 'ProfileNotFound' : null } |
  { 'AlreadyArchived' : null } |
  { 'NotSignedIn' : null };
export interface ArchiveItem {
  'id' : ArchiveItemId,
  'era' : string,
  'status' : ArchiveItemStatus,
  'title' : string,
  'relatedMemberIds' : Array<string>,
  'blob' : ExternalBlob,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'year' : [] | [bigint],
  'description' : string,
  'privacyLevel' : PrivacyLevel,
  'primarySpeaker' : [] | [OralHistorySpeaker],
  'extractedNames' : [] | [Array<string>],
  'itemType' : ArchiveItemType,
  'aiSummary' : [] | [string],
  'searchableTranscript' : [] | [string],
  'relatedBranchId' : [] | [string],
  'transcript' : [] | [string],
  'chapterMarkers' : [] | [Array<ChapterMarker>],
  'sourceStatus' : SourceStatus,
  'classification' : ArchiveItemClassification,
  'contributor' : Principal,
}
export type ArchiveItemClassification = { 'OralHistory' : null } |
  { 'Standard' : null };
export type ArchiveItemId = bigint;
export type ArchiveItemStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type ArchiveItemType = { 'Research' : null } |
  { 'Photo' : null } |
  { 'Document' : null } |
  { 'WorkBusiness' : null } |
  { 'WrittenStoryNote' : null } |
  { 'Audio' : null } |
  { 'Other' : null } |
  { 'Video' : null };
export type AuditActionType = { 'ProfileRemovalRequested' : null } |
  { 'ClaimRejected' : null } |
  { 'RelationshipTypeCorrected' : null } |
  { 'RelationshipRequestPending' : null } |
  { 'StewardPromoted' : null } |
  { 'SuccessorActivated' : null } |
  { 'StewardRemoved' : null } |
  { 'RelationshipRequestApproved' : null } |
  { 'DuplicateMerged' : null } |
  { 'ProfilePermanentlyDeleted' : null } |
  { 'RelationshipRequestRejected' : null } |
  { 'ProfileArchived' : null } |
  { 'ProfileRestored' : null } |
  { 'RelationshipAdded' : null } |
  { 'RelationshipRemoved' : null } |
  { 'ProfileRemovalReviewed' : null } |
  { 'ClaimApproved' : null } |
  { 'SuccessorDesignated' : null };
export interface AuditEntry {
  'id' : bigint,
  'affectedPersonIds' : Array<PersonId>,
  'actionType' : AuditActionType,
  'summary' : string,
  'timestamp' : bigint,
  'actorAccountId' : Principal,
}
export type AuthMethod = { 'Google' : null } |
  { 'Apple' : null };
export interface AuthMethods { 'apple' : boolean, 'google' : boolean }
export interface Cell { 'value' : Value, 'name' : string }
export interface ChapterMarker { 'title' : string, 'timestamp' : bigint }
export type ClaimError = { 'AlreadyPending' : null } |
  { 'ProfileNotFound' : null } |
  { 'AlreadyClaimed' : null } |
  { 'NotSignedIn' : null } |
  { 'DeceasedProfile' : null };
export type ClaimStatus = { 'Unclaimed' : null } |
  { 'Claimed' : null };
export type CreateError = { 'NotSignedIn' : null };
export type DeleteError = { 'HasOwnershipHistory' : null } |
  { 'ProfileNotFound' : null } |
  { 'HasMedia' : null } |
  { 'HasArchiveItems' : null } |
  { 'NotSignedIn' : null } |
  { 'ConfirmationRequired' : null } |
  { 'HasTimeline' : null } |
  { 'HasApprovedRelationships' : null };
export interface DuplicateCandidate {
  'deathDate' : [] | [string],
  'ownerAccount' : [] | [Principal],
  'birthDate' : [] | [string],
  'claimStatus' : string,
  'name' : string,
  'archiveLinks' : Array<string>,
  'children' : Array<string>,
  'sourceCount' : bigint,
  'personId' : PersonId,
  'spouses' : Array<string>,
  'photoCount' : bigint,
  'timelineCount' : bigint,
  'parents' : Array<string>,
}
export interface DuplicatePair {
  'candidateA' : DuplicateCandidate,
  'candidateB' : DuplicateCandidate,
}
export type EditError = { 'ProfileNotFound' : null } |
  { 'NotSignedIn' : null } |
  { 'NotOwner' : null } |
  { 'DeceasedProfile' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type EvidenceStatus = { 'Unresolved' : null } |
  { 'Documented' : null } |
  { 'FamilyHistory' : null } |
  { 'PersonalMemory' : null };
export type ExternalBlob = Uint8Array;
export type LivingStatus = { 'Living' : null } |
  { 'Deceased' : null };
export interface MergeConflict {
  'id' : bigint,
  'field' : string,
  'status' : MergeConflictStatus,
  'alternateValue' : string,
  'canonicalValue' : string,
  'resolvedAt' : [] | [bigint],
  'resolvedBy' : [] | [Principal],
}
export type MergeConflictStatus = { 'Resolved' : null } |
  { 'Pending' : null };
export type MergeError = { 'NotDuplicate' : null } |
  { 'ProfileNotFound' : null } |
  { 'NotSignedIn' : null } |
  { 'SameProfile' : null };
export interface MergeResult {
  'archivedPersonId' : PersonId,
  'conflicts' : Array<MergeConflict>,
  'canonicalPersonId' : PersonId,
}
export interface Mystery {
  'id' : MysteryId,
  'status' : MysteryStatus,
  'title' : string,
  'relatedMemberIds' : Array<string>,
  'createdAt' : bigint,
  'relatedArchiveItemIds' : Array<bigint>,
  'description' : string,
  'resolution' : [] | [Resolution],
  'updatedAt' : bigint,
  'knownFacts' : Array<string>,
  'possibilities' : Array<string>,
  'relatedBranchId' : [] | [string],
  'relatedSourceIds' : Array<bigint>,
  'contributor' : Principal,
}
export interface MysteryContribution {
  'id' : MysteryContributionId,
  'status' : MysteryContributionStatus,
  'createdAt' : bigint,
  'text' : string,
  'mysteryId' : MysteryId,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'contributionType' : MysteryContributionType,
  'contributor' : Principal,
}
export type MysteryContributionId = bigint;
export type MysteryContributionStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type MysteryContributionType = { 'Lead' : null } |
  { 'Note' : null } |
  { 'Memory' : null } |
  { 'Source' : null };
export type MysteryId = bigint;
export type MysteryStatus = { 'Researching' : null } |
  { 'Open' : null } |
  { 'PartiallyResolved' : null } |
  { 'Resolved' : null };
export interface Notification {
  'id' : bigint,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'read' : boolean,
  'recipient' : Principal,
  'message' : string,
}
export type NotificationId = bigint;
export type NotificationType = { 'RelationshipRequested' : null } |
  { 'RelationshipReviewed' : null } |
  { 'ProfileClaimReviewed' : null } |
  { 'ProfileClaimRequested' : null };
export interface OralHistorySpeaker {
  'name' : string,
  'personId' : [] | [string],
}
export type PersonId = string;
export interface PersonMatch {
  'name' : string,
  'personId' : PersonId,
  'parents' : Array<string>,
}
export interface PersonProfile {
  'occupation' : [] | [string],
  'privacySettings' : [] | [string],
  'nickname' : [] | [string],
  'claimedByUserId' : [] | [Principal],
  'birthDate' : [] | [string],
  'birthInfo' : [] | [string],
  'claimStatus' : ClaimStatus,
  'livingStatus' : LivingStatus,
  'name' : string,
  'longerStory' : [] | [string],
  'personId' : PersonId,
  'story' : [] | [string],
  'middleName' : [] | [string],
  'suffix' : [] | [string],
  'preferredName' : [] | [string],
  'currentLocation' : [] | [string],
  'birthplace' : [] | [string],
  'lastName' : [] | [string],
  'shortBio' : [] | [string],
  'timeline' : [] | [Array<string>],
  'firstName' : [] | [string],
}
export interface Photo {
  'id' : PhotoId,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export type PhotoId = bigint;
export type PrivacyLevel = { 'Private' : null } |
  { 'Public' : null } |
  { 'FamilyOnly' : null };
export interface ProfileClaim {
  'id' : bigint,
  'submittedDate' : bigint,
  'status' : ProfileClaimStatus,
  'reviewedDate' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'personId' : PersonId,
  'requestingUserId' : Principal,
}
export type ProfileClaimStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface ProfileEdits {
  'occupation' : [] | [string],
  'privacySettings' : [] | [string],
  'nickname' : [] | [string],
  'birthDate' : [] | [string],
  'birthInfo' : [] | [string],
  'livingStatus' : [] | [LivingStatus],
  'longerStory' : [] | [string],
  'story' : [] | [string],
  'middleName' : [] | [string],
  'suffix' : [] | [string],
  'preferredName' : [] | [string],
  'currentLocation' : [] | [string],
  'birthplace' : [] | [string],
  'lastName' : [] | [string],
  'shortBio' : [] | [string],
  'timeline' : [] | [Array<string>],
  'firstName' : [] | [string],
}
export interface ProfileRemovalRequest {
  'id' : bigint,
  'submittedDate' : bigint,
  'status' : ProfileRemovalStatus,
  'reviewedDate' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'personId' : PersonId,
  'requestingUserId' : Principal,
  'reason' : string,
}
export type ProfileRemovalStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface Relationship {
  'id' : bigint,
  'status' : RelationshipStatus,
  'fromPersonId' : PersonId,
  'toPersonId' : PersonId,
  'relationshipType' : RelationshipType,
}
export type RelationshipAdminError = { 'RelationshipNotFound' : null } |
  { 'NotSignedIn' : null } |
  { 'DuplicateRelationship' : null } |
  { 'PersonNotFound' : null };
export type RelationshipError = { 'DuplicateRequest' : null } |
  { 'NotSignedIn' : null } |
  { 'PersonNotFound' : null };
export interface RelationshipRequest {
  'id' : bigint,
  'submittedDate' : bigint,
  'status' : RelationshipRequestStatus,
  'reviewedDate' : [] | [bigint],
  'relatedPersonId' : PersonId,
  'requestingPersonId' : PersonId,
  'proposedRelationship' : RelationshipType,
  'reviewer' : [] | [Principal],
}
export type RelationshipRequestStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export type RelationshipStatus = { 'Disputed' : null } |
  { 'Confirmed' : null } |
  { 'Pending' : null };
export type RelationshipType = { 'Parent' : null } |
  { 'Sibling' : null } |
  { 'SpousePartner' : null } |
  { 'Child' : null };
export type RemovalError = { 'AlreadyPending' : null } |
  { 'ProfileNotFound' : null } |
  { 'NotSignedIn' : null } |
  { 'NotOwner' : null } |
  { 'DeceasedProfile' : null };
export type RemoveError = { 'ProfileNotFound' : null } |
  { 'NotSignedIn' : null };
export interface Resolution {
  'supportingEvidence' : Array<string>,
  'summary' : string,
  'resolvedAt' : bigint,
  'resolvedBy' : Principal,
}
export type Result = { 'ok' : PersonProfile } |
  { 'err' : EditError };
export type Result_1 = { 'ok' : null } |
  { 'err' : ArchiveError };
export type Result_10 = { 'ok' : null } |
  { 'err' : MergeError };
export type Result_11 = { 'ok' : MergeResult } |
  { 'err' : MergeError };
export type Result_12 = { 'ok' : AuthMethods } |
  { 'err' : AccountError };
export type Result_13 = { 'ok' : AccountId } |
  { 'err' : AccountError };
export type Result_14 = { 'ok' : SuccessorDesignation } |
  { 'err' : StewardError };
export type Result_15 = { 'ok' : PersonProfile } |
  { 'err' : CreateError };
export type Result_16 = { 'ok' : Relationship } |
  { 'err' : RelationshipAdminError };
export type Result_17 = { 'ok' : Account } |
  { 'err' : AccountError };
export type Result_18 = { 'ok' : null } |
  { 'err' : Error };
export type Result_2 = { 'ok' : ProfileRemovalRequest } |
  { 'err' : RemovalError };
export type Result_3 = { 'ok' : ProfileClaim } |
  { 'err' : ClaimError };
export type Result_4 = { 'ok' : null } |
  { 'err' : StewardError };
export type Result_5 = { 'ok' : null } |
  { 'err' : RelationshipAdminError };
export type Result_6 = { 'ok' : null } |
  { 'err' : RemoveError };
export type Result_7 = { 'ok' : RelationshipRequest } |
  { 'err' : RelationshipError };
export type Result_8 = { 'ok' : StewardRecord } |
  { 'err' : StewardError };
export type Result_9 = { 'ok' : null } |
  { 'err' : DeleteError };
export interface Result__1 { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type SourceStatus = { 'Copy' : null } |
  { 'Unverified' : null } |
  { 'Transcribed' : null } |
  { 'Original' : null };
export type StewardError = { 'LastSteward' : null } |
  { 'NotSteward' : null } |
  { 'AlreadySteward' : null } |
  { 'NotSignedIn' : null } |
  { 'NotApprovedClaimedMember' : null } |
  { 'NotDesignated' : null };
export interface StewardIdentity {
  'accountId' : Principal,
  'displayName' : string,
  'personId' : PersonId,
  'canonicalName' : string,
}
export interface StewardRecord {
  'assignedAt' : bigint,
  'assignedBy' : Principal,
  'stewardAccountId' : Principal,
  'successorPriority' : [] | [bigint],
  'roleStatus' : StewardRoleStatus,
}
export type StewardRoleStatus = { 'Active' : null } |
  { 'Removed' : null };
export interface Story {
  'id' : StoryId,
  'era' : [] | [string],
  'status' : StoryStatus,
  'title' : string,
  'relatedMemberIds' : Array<string>,
  'storyText' : string,
  'createdAt' : bigint,
  'year' : [] | [bigint],
  'relatedArchiveItemIds' : Array<bigint>,
  'updatedAt' : bigint,
  'evidenceStatus' : EvidenceStatus,
  'location' : [] | [string],
  'contributor' : Principal,
}
export type StoryId = bigint;
export type StoryStatus = { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'Pending' : null };
export interface SuccessorDesignation {
  'status' : SuccessorStatus,
  'assignedAt' : bigint,
  'assignedBy' : Principal,
  'personId' : PersonId,
  'priority' : bigint,
}
export type SuccessorStatus = { 'Activated' : null } |
  { 'Removed' : null } |
  { 'Designated' : null };
export interface TimelineEvent {
  'id' : string,
  'era' : [] | [string],
  'title' : string,
  'year' : [] | [bigint],
  'linkTarget' : TimelineLinkTarget,
  'description' : string,
  'evidenceStatus' : EvidenceStatus,
  'eventType' : TimelineEventType,
}
export type TimelineEventType = { 'MilitaryService' : null } |
  { 'Story' : null } |
  { 'Birth' : null } |
  { 'FamilyEvent' : null } |
  { 'Migration' : null } |
  { 'Mystery' : null } |
  { 'Death' : null } |
  { 'PhotoDocument' : null } |
  { 'Marriage' : null } |
  { 'CensusDocument' : null } |
  { 'Location' : null };
export type TimelineLinkTarget = { 'Story' : StoryId } |
  { 'Mystery' : MysteryId } |
  { 'Person' : string } |
  { 'ArchiveItem' : bigint };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result_18>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'activateSuccessor' : ActorMethod<[PersonId], Result_8>,
  'addCanonicalStory' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      [] | [string],
      [] | [bigint],
      [] | [string],
      EvidenceStatus,
      Array<bigint>,
    ],
    Story
  >,
  'addPhoto' : ActorMethod<[PersonId, string, string, ExternalBlob], Photo>,
  'addRelationship' : ActorMethod<
    [PersonId, PersonId, RelationshipType],
    Result_16
  >,
  'approveArchiveItem' : ActorMethod<[ArchiveItemId], [] | [ArchiveItem]>,
  'approveProfileClaim' : ActorMethod<[bigint], [] | [ProfileClaim]>,
  'approveProfileRemoval' : ActorMethod<[bigint], [] | [ProfileRemovalRequest]>,
  'approveRelationshipRequest' : ActorMethod<
    [bigint],
    [] | [RelationshipRequest]
  >,
  'approveStory' : ActorMethod<[StoryId], [] | [Story]>,
  'archiveProfile' : ActorMethod<[PersonId], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bindAuthMethod' : ActorMethod<[AuthMethod], Result_17>,
  'correctRelationshipType' : ActorMethod<
    [bigint, RelationshipType],
    Result_16
  >,
  'createCanonicalMystery' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      [] | [string],
      Array<string>,
      Array<string>,
      Array<bigint>,
      Array<bigint>,
      MysteryStatus,
    ],
    Mystery
  >,
  'createMyself' : ActorMethod<[string], Result_15>,
  'designateSuccessor' : ActorMethod<[PersonId, bigint], Result_14>,
  'execute' : ActorMethod<[string], Result__1>,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAccountId' : ActorMethod<[], Result_13>,
  'getMyAuthMethods' : ActorMethod<[], Result_12>,
  'getMyProfile' : ActorMethod<[], [] | [PersonProfile]>,
  'getMyProfileClaim' : ActorMethod<[PersonId], [] | [ProfileClaim]>,
  /**
   * / Renders an audit action type variant as its tag text for OQL rows.
   */
  'getMyRelationshipRequests' : ActorMethod<[], Array<RelationshipRequest>>,
  'getPersonProfile' : ActorMethod<[PersonId], [] | [PersonProfile]>,
  'getProfilePhoto' : ActorMethod<[PersonId], [] | [Photo]>,
  'getRelationshipRequest' : ActorMethod<[bigint], [] | [RelationshipRequest]>,
  'getSingleStewardWarning' : ActorMethod<[], [] | [string]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listApprovedArchiveItems' : ActorMethod<[], Array<ArchiveItem>>,
  'listApprovedStories' : ActorMethod<[], Array<Story>>,
  'listArchivedProfileIds' : ActorMethod<[], Array<PersonId>>,
  'listArchivedProfiles' : ActorMethod<[], Array<PersonProfile>>,
  'listAuditHistory' : ActorMethod<[], Array<AuditEntry>>,
  'listConfirmedRelationships' : ActorMethod<[], Array<Relationship>>,
  'listDuplicateCandidates' : ActorMethod<[], Array<DuplicatePair>>,
  'listEligibleStewardCandidates' : ActorMethod<[], Array<StewardIdentity>>,
  'listMysteries' : ActorMethod<[], Array<Mystery>>,
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  'listPendingArchiveItems' : ActorMethod<[], Array<ArchiveItem>>,
  'listPendingMysteryContributions' : ActorMethod<
    [],
    Array<MysteryContribution>
  >,
  'listPendingStories' : ActorMethod<[], Array<Story>>,
  'listPersonRelationships' : ActorMethod<[PersonId], Array<Relationship>>,
  'listPhotos' : ActorMethod<[PersonId], Array<Photo>>,
  'listProfileClaims' : ActorMethod<[], Array<ProfileClaim>>,
  'listProfileRemovalRequests' : ActorMethod<[], Array<ProfileRemovalRequest>>,
  'listRelationshipRequests' : ActorMethod<[], Array<RelationshipRequest>>,
  'listStewardIdentities' : ActorMethod<[], Array<StewardIdentity>>,
  'listStewards' : ActorMethod<[], Array<StewardRecord>>,
  'listSuccessors' : ActorMethod<[], Array<SuccessorDesignation>>,
  'listTimelineEvents' : ActorMethod<[], Array<TimelineEvent>>,
  'markMysteryResolved' : ActorMethod<
    [MysteryId, string, Array<string>],
    [] | [Mystery]
  >,
  'markNotificationRead' : ActorMethod<[NotificationId], [] | [Notification]>,
  'mergeProfiles' : ActorMethod<[PersonId, PersonId], Result_11>,
  'notDuplicate' : ActorMethod<[PersonId, PersonId], Result_10>,
  'permanentlyDeleteProfile' : ActorMethod<[PersonId, boolean], Result_9>,
  'promoteToSteward' : ActorMethod<[PersonId], Result_8>,
  'proposeRelationship' : ActorMethod<
    [PersonId, PersonId, RelationshipType],
    Result_7
  >,
  'rejectArchiveItem' : ActorMethod<[ArchiveItemId], [] | [ArchiveItem]>,
  'rejectProfileClaim' : ActorMethod<[bigint], [] | [ProfileClaim]>,
  'rejectProfileRemoval' : ActorMethod<[bigint], [] | [ProfileRemovalRequest]>,
  'rejectRelationshipRequest' : ActorMethod<
    [bigint],
    [] | [RelationshipRequest]
  >,
  'rejectStory' : ActorMethod<[StoryId], [] | [Story]>,
  'removeDuplicateProfile' : ActorMethod<[PersonId], Result_6>,
  'removePhoto' : ActorMethod<[PersonId, PhotoId], boolean>,
  'removeRelationship' : ActorMethod<[bigint], Result_5>,
  'removeSteward' : ActorMethod<[Principal], Result_4>,
  'requestProfileClaim' : ActorMethod<[PersonId], Result_3>,
  'requestProfileRemoval' : ActorMethod<[PersonId, string], Result_2>,
  'resolveMergeConflict' : ActorMethod<[bigint, string], [] | [MergeConflict]>,
  'restoreProfile' : ActorMethod<[PersonId], Result_1>,
  'reviewMysteryContribution' : ActorMethod<
    [MysteryContributionId, boolean],
    [] | [MysteryContribution]
  >,
  'schema' : ActorMethod<[], string>,
  'searchPossibleMatches' : ActorMethod<[string], Array<PersonMatch>>,
  'setProfilePhoto' : ActorMethod<[PersonId, PhotoId], [] | [Photo]>,
  'setRelationshipRequestPending' : ActorMethod<
    [bigint],
    [] | [RelationshipRequest]
  >,
  'submitArchiveItem' : ActorMethod<
    [
      string,
      string,
      ArchiveItemType,
      ExternalBlob,
      string,
      [] | [bigint],
      Array<string>,
      Array<string>,
      [] | [string],
      SourceStatus,
      PrivacyLevel,
      ArchiveItemClassification,
      [] | [OralHistorySpeaker],
    ],
    ArchiveItem
  >,
  'submitMysteryContribution' : ActorMethod<
    [MysteryId, MysteryContributionType, string],
    MysteryContribution
  >,
  'submitStory' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      [] | [string],
      [] | [bigint],
      [] | [string],
      EvidenceStatus,
      Array<bigint>,
    ],
    Story
  >,
  'updateCanonicalMystery' : ActorMethod<
    [
      MysteryId,
      string,
      string,
      Array<string>,
      [] | [string],
      Array<string>,
      Array<string>,
      Array<bigint>,
      Array<bigint>,
      MysteryStatus,
    ],
    [] | [Mystery]
  >,
  'updateCanonicalStory' : ActorMethod<
    [
      StoryId,
      string,
      string,
      Array<string>,
      [] | [string],
      [] | [bigint],
      [] | [string],
      EvidenceStatus,
      Array<bigint>,
    ],
    [] | [Story]
  >,
  'updateOwnProfile' : ActorMethod<[PersonId, ProfileEdits], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];